### ISSUE TITLE
Start up with the group project

### ISSUE THREAD

**Issue by TamaraDimov** [TamaraDimov/recipe_app_ror#2]
- We are a team of 2 members @TamaraDimov and @Salimer 

- [Kanban board](https://github.com/users/TamaraDimov/projects/3/views/1) with all the tasks according the requirements

**Comment by addod19** [comment]
## Hi @Salimer and @TamaraDimov, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] The link to the kanban board is provided with the number of people stated :100: 
- [ ] Required columns provided :rocket: 
- [ ] All cards are assigned and points distributed fairly :fireworks: 
- [ ] Title and description present in all the cards :rocket: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
